# Generated by Django 3.1.5 on 2021-07-26 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parevaluador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notasfinal', models.CharField(max_length=2)),
                ('Detallefin', models.TextField()),
                ('Parevaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parevaluador.parevaluador')),
            ],
        ),
    ]
