# Generated by Django 3.1.5 on 2021-07-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=400)),
                ('Apellidos', models.CharField(max_length=800)),
                ('Correo', models.CharField(max_length=100)),
                ('Archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('Detalle', models.TextField()),
                ('Entrevista', models.TextField()),
                ('Notas', models.TextField()),
            ],
        ),
    ]
