# Generated by Django 3.1.5 on 2021-07-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0002_auto_20210726_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='Notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
